#!/bin/bash

echo "🔧 Supabase Database Setup Script"
echo "=================================="
echo ""
echo "This script will help you set up your database tables."
echo ""
echo "Please check your database password from:"
echo "https://supabase.com/dashboard/project/epfclgvooboffhlxccmb/settings/database"
echo ""
echo "Your password might be different than what we have."
echo ""
echo "Options:"
echo "1. Try with Supabase CLI (requires correct password)"
echo "2. Use the SQL directly in Supabase Dashboard"
echo "3. Debug connection issues"
echo ""
echo "For now, let's use Option 2 (Dashboard):"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/epfclgvooboffhlxccmb/sql/new"
echo "2. Copy all the SQL below and paste it there:"
echo ""
echo "========== COPY FROM HERE =========="
cat supabase/migrations/20250902193113_intent_classification_tables.sql
echo "========== COPY TO HERE =========="
echo ""
echo "3. Click 'Run' in the Supabase Dashboard"
echo ""
echo "Once done, run: npm run db:check"