name: Weekly iOS Rebuild

on:
  schedule:
    # Every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Install dependencies
        run: |
          cd packages/mobile
          npm install
          
      - name: Build iOS
        run: |
          cd packages/mobile
          eas build --profile device --platform ios --non-interactive
          
      - name: Notify
        run: echo "Build submitted! Check Expo dashboard for download link"